const records = [
  {
    id: '1',
    title: 'The Dark Side of the Moon',
    artist: 'Pink Floyd',
    category: 'Rock',
    price: 29.99,
    year: 1973,
    condition: 'Near Mint',
    image: '/images/dark-side.jpeg',
    description: 'One of the most iconic rock albums ever made. Features the hit single "Money" and "Time".',
    inStock: true
  },
  {
    id: '2',
    title: 'Kind of Blue',
    artist: 'Miles Davis',
    category: 'Jazz',
    price: 34.99,
    year: 1959,
    condition: 'Very Good',
    image: '/images/kind-of-blue.jpg',
    description: 'A landmark jazz album that revolutionized modal jazz. Features "So What" and "Blue in Green".',
    inStock: true
  },
  {
    id: '3',
    title: 'Symphony No. 9',
    artist: 'Ludwig van Beethoven',
    category: 'Classical',
    price: 24.99,
    year: 1824,
    condition: 'Mint',
    image: '/images/beethoven-9.jpg',
    description: 'Beethoven\'s final symphony, featuring the famous "Ode to Joy" in the fourth movement.',
    inStock: true
  },
  {
    id: '4',
    title: 'Thriller',
    artist: 'Michael Jackson',
    category: 'Rock',
    price: 39.99,
    year: 1982,
    condition: 'Mint',
    image: '/images/thriller.jpg',
    description: 'The best-selling album of all time. Features hits like "Billie Jean" and "Beat It".',
    inStock: true
  },
  {
    id: '5',
    title: 'Abbey Road',
    artist: 'The Beatles',
    category: 'Rock',
    price: 32.99,
    year: 1969,
    condition: 'Near Mint',
    image: '/images/abbey-road.jpeg',
    description: 'The Beatles\' final recorded album. Features the famous medley on side two.',
    inStock: true
  },
  {
    id: '6',
    title: 'Rumours',
    artist: 'Fleetwood Mac',
    category: 'Rock',
    price: 27.99,
    year: 1977,
    condition: 'Very Good',
    image: '/images/rumours.jpg',
    description: 'A masterpiece of soft rock. Features hits like "Go Your Own Way" and "Dreams".',
    inStock: true
  },
  {
    id: '7',
    title: 'Time Out',
    artist: 'Dave Brubeck Quartet',
    category: 'Jazz',
    price: 31.99,
    year: 1959,
    condition: 'Near Mint',
    image: '/images/time-out.jpg',
    description: 'Famous for its unusual time signatures. Features the hit "Take Five".',
    inStock: true
  },
  {
    id: '8',
    title: 'The Planets',
    artist: 'Gustav Holst',
    category: 'Classical',
    price: 28.99,
    year: 1916,
    condition: 'Mint',
    image: '/images/planets.jpg',
    description: 'A seven-movement orchestral suite, each movement named after a planet.',
    inStock: true
  },
  {
    id: '9',
    title: 'Led Zeppelin IV',
    artist: 'Led Zeppelin',
    category: 'Rock',
    price: 35.99,
    year: 1971,
    condition: 'Very Good',
    image: '/images/led-zeppelin-iv.jpg',
    description: 'Features the iconic "Stairway to Heaven" and other classic rock anthems.',
    inStock: true
  },
  {
    id: '10',
    title: 'A Love Supreme',
    artist: 'John Coltrane',
    category: 'Jazz',
    price: 33.99,
    year: 1965,
    condition: 'Near Mint',
    image: '/images/love-supreme.jpg',
    description: 'A spiritual jazz masterpiece. One of Coltrane\'s most influential works.',
    inStock: true
  },
  {
    id: '11',
    title: 'The Four Seasons',
    artist: 'Antonio Vivaldi',
    category: 'Classical',
    price: 26.99,
    year: 1725,
    condition: 'Mint',
    image: '/images/four-seasons.jpg',
    description: 'A set of four violin concertos, each representing a season of the year.',
    inStock: true
  },
  {
    id: '12',
    title: 'Back to Black',
    artist: 'Amy Winehouse',
    category: 'Rock',
    price: 29.99,
    year: 2006,
    condition: 'Near Mint',
    image: '/images/back-to-black.jpeg',
    description: 'A modern soul classic. Features hits like "Rehab" and "Back to Black".',
    inStock: true
  },
  {
    id: '13',
    title: 'Blue Train',
    artist: 'John Coltrane',
    category: 'Jazz',
    price: 30.99,
    year: 1958,
    condition: 'Very Good',
    image: '/images/blue-train.jpg',
    description: 'A hard bop masterpiece featuring Coltrane\'s signature sound.',
    inStock: true
  },
  {
    id: '14',
    title: 'Symphony No. 5',
    artist: 'Pyotr Ilyich Tchaikovsky',
    category: 'Classical',
    price: 25.99,
    year: 1888,
    condition: 'Mint',
    image: '/images/tchaikovsky-5.jpg',
    description: 'A powerful symphony featuring the famous "Fate" theme.',
    inStock: true
  },
  {
    id: '15',
    title: 'Nevermind',
    artist: 'Nirvana',
    category: 'Rock',
    price: 31.99,
    year: 1991,
    condition: 'Near Mint',
    image: '/images/nevermind.jpg',
    description: 'The album that defined grunge. Features "Smells Like Teen Spirit".',
    inStock: true
  }
]; 
